---
- name: Install intellij
  become: true
  tags: install
  block:

    - name: Install snapd
      package:
        name: snapd

    - name: Install intellij community edition
      snap:
        classic: true
        name: intellij-idea-community
