---
- name: Install Intellij Community Edition
  tags: install
  become: true
  block:

    - name: Install flatpak
      community.general.flatpak:
        name: com.jetbrains.IntelliJ-IDEA-Community
        state: present